[package]
name = "stellar-handshake"
version = "0.1.0"
edition = "2021"


[dependencies]

data-encoding = "2.3"
dryoc = "0.5"
ring = "0.17"
tokio = {version = "1.32", features = ["net", "io-util", "macros", "rt-multi-thread"] }
thiserror = "1.0"
bytes = "1.5"