[package]
name = "stellar-handshake"
version = "0.1.0"
edition = "2021"


[dependencies]

data-encoding = "2.3"
dryoc = "0.5.1"
ring = "0.17.0"
tokio = {version = "1.32.0", features = ["net", "io-util", "rt", "macros", "rt-multi-thread"] }
base64 = "0.21.4"
thiserror = "1.0.49"
bytes = "1.5.0"