
[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
data-encoding = "2.3"
dryoc = "0.5"
ring = "0.17"
tokio = {version = "1.32", features = ["net", "io-util", "macros", "rt-multi-thread"] }
thiserror = "1.0"
bytes = "1.5"
anyhow = "1.0.75"
