[package]
name = "xdr"
version = "0.1.0"
edition = "2021"

[lib]
name = "xdr"
path = "src/lib.rs"

[dependencies]
dryoc = { workspace = true }
ring = { workspace = true }
utils = {path = "../utils"}
thiserror = {workspace = true}